### ISSUE TITLE
Optimizing EntityCache

### ISSUE THREAD

**Issue by guillaumerose** [MorbZ/OSMonaut#8]
I've found that Osmosis use org.openstreetmap.osmosis.core.filter.common.DynamicIdTracker to manage set of long.
We should probably use it. 

https://github.com/openstreetmap/osmosis/blob/master/osmosis-core/src/main/java/org/openstreetmap/osmosis/core/filter/common/DynamicIdTracker.java

**Comment by MorbZ** [comment]
Looks fine. But I don't think it can be stored in MapDB effectively because it's mutable. And keeping it in memory could use up to ~500Mb just for the nodes (all planet node-IDs with BitSet) which I think is a bit too much.

**Comment by laurentg** [comment]
Another (maybe simpler optimization) is to use Trove, it implements special collections (set, hash...) of simple types such as `long` (http://trove4j.sourceforge.net/javadocs/gnu/trove/set/hash/TLongHashSet.html). It maybe a good fit to keep track of ids to load in `EntityCache`.

**Comment by MorbZ** [comment]
Yes that seems fine

**Comment by MorbZ** [comment]
After some testing I implemented an own ID-tracker that only uses BitSet. Although it's very simple it uses ~25% less memory than the Osmonaut IdTracker for larger PBF-files and is faster. Could also be tweaked to use even less memory. I use it even in low-memory-mode instead of MapDB.
